#!/bin/bash
#
# Zurgarr quick setup — creates a .env file for first run.
#
# Sets up your configuration so you can start the container and
# manage everything else from the web UI at http://localhost:8080/settings
#

ENV_FILE=".env"
EXAMPLE_FILE=".env.example"

echo ""
echo "  Zurgarr Quick Setup"
echo "  ==================="
echo ""
echo "  This will create a .env file with your essential settings."
echo "  Everything else can be configured from the web UI after starting."
echo ""

# Check if .env already exists
if [[ -f "$ENV_FILE" ]]; then
    read -p "  .env already exists. Overwrite? (y/n) [n]: " overwrite
    overwrite=$(echo "$overwrite" | tr '[:upper:]' '[:lower:]')
    if [[ "$overwrite" != "y" && "$overwrite" != "yes" ]]; then
        echo "  Aborted. Your existing .env was not changed."
        exit 0
    fi
fi

# Ask for web UI auth
read -p "  Choose a username for the web UI [admin]: " ui_user
ui_user=${ui_user:-admin}

while true; do
    read -s -p "  Choose a password for the web UI: " ui_pass
    echo ""
    if [[ -z "$ui_pass" ]]; then
        echo "  Password cannot be empty. Please try again."
    else
        break
    fi
done

# Ask for debrid API key
echo ""
read -p "  Do you have a Real-Debrid API key? (y/n) [n]: " has_rd
has_rd=$(echo "$has_rd" | tr '[:upper:]' '[:lower:]')

rd_key=""
if [[ "$has_rd" == "y" || "$has_rd" == "yes" ]]; then
    read -p "  Enter your Real-Debrid API key: " rd_key
fi

# Write .env file
cat > "$ENV_FILE" << EOF
# Zurgarr configuration — generated by setup script
# Edit this file or use the web UI at /settings

# Zurg
ZURG_ENABLED=true
RD_API_KEY=$rd_key
RCLONE_MOUNT_NAME=zurgarr

# Status Web UI & Settings Editor
STATUS_UI_ENABLED=true
STATUS_UI_AUTH=$ui_user:$ui_pass
EOF

# Get the port
ui_port="8080"

echo ""
echo "  Setup complete! Created .env file."
echo ""
echo "  Next steps:"
echo "    1. Start the container:  docker compose up -d"
echo "    2. Open your browser:    http://localhost:$ui_port/settings"
echo "    3. Log in with:          $ui_user / (your password)"
echo "    4. Configure everything else from the web UI"
echo ""
if [[ -z "$rd_key" ]]; then
    echo "  Note: You'll need to add your debrid API key in the web settings"
    echo "  editor under the Zurg category before services will start."
    echo ""
fi
